# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5b8355ab9dae90268167ea1b0a653f3ac65f6c8a6c17f7e07c9e041e505415300d3e7c44dd560724dc2eae8fec0addcd03f52f6f44612e9826c5947b46a9240

test:
  secret_key_base: f2dc928b4f2a0ad1a30135e9671961aadc17221600fd3c7c98f9e807bec30ca995f8782b88cb27695a2537832747c846b92eba10517f7962e41b58750e867fff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
